# Generated by Django 4.0.6 on 2022-07-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sijanapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sijan',
            name='imageadded',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
